import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';

export default function Testing() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>TESTING</h1>

				<p className={styles.description}>
					This page only exists to test (deep) the sidebar. Should be removed the second there are
					other pages to replace it.
				</p>

				<p>
					<Link href="/" passHref>
						<a>Go back to index</a>
					</Link>
				</p>

				<p>
					<Link href="/test" passHref>
						<a>Go back to test</a>
					</Link>
				</p>

				<p>
					<Link href="/example" passHref>
						<a>Go to example</a>
					</Link>
				</p>
			</main>
		</div>
	);
}
