import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function WelcomeView(props) {
    return (
        <div className={styles.container}>
        <Head>
            <title>SpeakEasy</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className={styles.main}>
            <h1 className={styles.title}>
                Welcome to SpeakEasy
            </h1>
            <div className={styles.description}>
                {props.components}
            </div>
        </main>
    </div>)
}